apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-agent
  namespace: aml-platform
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_TERRAFORM_OUTPUT_compliance_agent_irsa_role_arn
