apiVersion: v1
kind: ConfigMap
metadata:
  name: governance-config
  namespace: aml-platform
data:
  AWS_REGION: "ap-southeast-2"
  SUPERTOKENS_CONNECTION_URI: "https://srv1603169.hstgr.cloud"
  SUPERTOKENS_API_DOMAIN: "http://governance.aml-platform.svc.cluster.local:8005"
