apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: aml-platform
  labels:
    app: neo4j
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      securityContext:
        fsGroup: 7474
      containers:
        - name: neo4j
          image: neo4j:5.18-community
          ports:
            - containerPort: 7687
              name: bolt
            - containerPort: 7474
              name: http
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-credentials
                  key: password
            - name: NEO4J_dbms_ssl_policy_bolt_enabled
              value: "true"
            - name: NEO4J_dbms_ssl_policy_https_enabled
              value: "true"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "1G"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "2G"
            - name: NEO4J_PLUGINS
              value: "[]"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          readinessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 60
            periodSeconds: 20
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 7474
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: efs-neo4j
        resources:
          requests:
            storage: 50Gi
