apiVersion: v1
kind: Service
metadata:
  name: transaction-monitoring
  namespace: aml-platform
  labels:
    app: transaction-monitoring
spec:
  selector:
    app: transaction-monitoring
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
