apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-monitoring
  namespace: aml-platform
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_TERRAFORM_OUTPUT_transaction_monitoring_irsa_role_arn
