apiVersion: v1
kind: ServiceAccount
metadata:
  name: document-detection-engine
  namespace: aml-platform
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_TERRAFORM_OUTPUT_document_engine_irsa_role_arn
