apiVersion: v1
kind: Service
metadata:
  name: document-detection-engine
  namespace: aml-platform
spec:
  selector:
    app: document-detection-engine
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
